### ISSUE TITLE
Invalid use of rasterio in _warper leading to segmentation faults

### ISSUE THREAD

**Issue by sgillies** [geopandas/contextily#160]
A contextily user reported https://github.com/mapbox/rasterio/issues/2000 and I have confirmed the issue. There may be something I can do on the rasterio end, or in GDAL, but misuse of rasterio is at the heart of the matter.

The problem is in
https://github.com/geopandas/contextily/blob/96b0e5e4536a6167058d6b10a5f96ed6014c35e2/contextily/tile.py#L404-L419. When the `memfile` context manager exits, your `mraster` dataset will be deleted. The VRT you return from the function references a non-existent in-memory file.

The reason why no one saw the problem with rasterio versions < 1.1.6 is that `MemoryFile.close` had a bug and did not clean up in-memory datasets. That bug was fixed in 1.1.6.

**Comment by drnextgis** [comment]
The issue can be easily reproduced with the following script:
```python
import rasterio
from rasterio.enums import Resampling
from contextily.tile import _warper
with rasterio.open("https://raw.githubusercontent.com/mapbox/rasterio/master/tests/data/RGB.byte.tif") as src: 
    img = src.read([1,2,3])

img, vrt = _warper(img, src.transform, src.crs, "epsg:4326", Resampling.cubic)
vrt.close()
```

**Comment by jorisvandenbossche** [comment]
@sgillies thanks a lot for the explanation. We also had someone else report (I suppose) the same here: https://github.com/geopandas/contextily/issues/159

It seems we only use the VRT afterwards to get the bounds and the transform. So that is something we can access when the memfile is still open, and return those actual values instead of the VRT from the function.

@sgillies one question for the rasterio side: would *ideally* a nice error be given when working with a closed file instead of a segfault?

**Comment by sgillies** [comment]
Yes, ideally rasterio would prevent dangerous usage. GDAL's C API lacks several functions that would help, so until we add those and get them installed on user machines, we'll have to resort to some hacks.

**Comment by sgillies** [comment]
Update: rasterio PR https://github.com/mapbox/rasterio/pull/2001 fixes the crasher in @drnextgis 's program.
