### ISSUE TITLE
error in basemap location

### ISSUE THREAD

**Issue by alcantarar** [geopandas/contextily#173]
I'm struggling to get the basemap to align with my coordinate data. For example, when I try to plot a point located near [40°06'17.5"N 105°15'56.2"W] (stored as `40.104860, -105.265600`), the point should be on land: 
![image](https://user-images.githubusercontent.com/38192529/109768251-e1a64780-7bb5-11eb-8c32-9c62ec4f409a.png)

But when I try to plot it with a basemap, it is located somewhere in the ocean:

```
df = pd.DataFrame(list(zip([40.104860, 40.104867], [-105.265600, -105.265500])), columns = ['lat', 'lon'])
```
~~db = gpd.GeoDataFrame(df, geometry=geopandas.points_from_xy(df.lon, df.lat), crs=3857)~~
```
db = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df.lon, df.lat), crs=3857)
ax = db.plot()
ctx.add_basemap(ax, crs = db.crs.to_string(), source = ctx.providers.OpenStreetMap.Mapnik)
```
![image](https://user-images.githubusercontent.com/38192529/109769351-51690200-7bb7-11eb-94f2-3d5a0f313527.png)

I feel like I'm missing something basic, but I can't figure it out!

**Comment by jorisvandenbossche** [comment]
The problem lies in this line:

```
db = gpd.GeoDataFrame(df, geometry=geopandas.points_from_xy(df.lon, df.lat), crs=3857)
```

your point data are in lat/lon degrees, but you specify that they are in the EPSG:3857 (web mercator) coordinate system. The CRS you pass to `GeoDataFrame(..)` doens't do any transformation, but is assumed to be the CRS for your data. So you need to specify it are degrees (WGS84, or EPSG:4326), and then convert to mercator:

```
db = gpd.GeoDataFrame(df, geometry=geopandas.points_from_xy(df.lon, df.lat), crs=4326).to_crs(3857)
```

Alternatively, you can also leave it in EPSG:4326 (don't convert to mercator), but that will depend on your exact extent if that will look OK (it will warp (and thus distort) the images a bit).

**Comment by alcantarar** [comment]
`..., crs=4326).to_crs(3857)` did it! Thanks for helping me out. Should point out that my original post has a typo if anyone is trying to copy/paste. `geopandas.points_from_xy` should be `gpd.points_from_xy` after `import geopandas as gpd`.
