### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by martinfleis** [geopandas/contextily#200]
Since the last week, our CI is failing. `test_place` seems to return unexpected values, causing its tests and `add_basemap` tests to fail.

**Comment by darribas** [comment]
We need to check this is an actual fail or a (minor) update of the underlying imagery that we use for testing that is making the specific tests fail. The latter has happened in the past and we have resorted to 1) ensuring the code still does what it's meant to 2) update the tests so they pass with the current imagery.

**Comment by EwoutH** [comment]
They all fail with the same error:

```
E       ValueError: The specified zoom level of 20 is not valid for the current tile provider (valid zooms: 0 - 18).
```
Since the CI is also tested on a schedule and did suddenly fail without any code changes on our side, it must be an environment change. I suspect a dependency updated their default (base)map, which only has other zoom levels and only supports zoomlevels up to 18.

Or (imo less likely), the zoomlevels for the (base)map we're using got updated and range now at most to 18.

The CI passed on 2022-07-14, and failed from 2022-07-21.

Could it be an update in [xyzservices](https://github.com/geopandas/xyzservices)? They didn't release any update in that period however. Any other suspicions?

**Comment by martinfleis** [comment]
One failure is caused by a recent xyzservices update and other by some change in the output of geocoding or tiles served by Stamen. Will update the tests accordingly.
