### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by lu5203** [geopandas/contextily#227]
HTTPSConnectionPool(host='stamen-tiles-a.a.ssl.fastly.net', port=443): Max retries exceeded with url: /terrain/1/0/0.png (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
When I use the contextily, it shows the error now.

**Comment by martinfleis** [comment]
Stamen tiles are deprecated and users are encouraged to migrate to Stadia tiles providing Stamen designs. Contextily made a switch from Stamen tiles in the last release. Please update your version and providers you use and let us know if the issue persists. I will close it now as this is likely due to the Stamen migration to Stadia but we can reopen if it proves to be a contextily issue.
